AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bot-dollar-currency

  Sample SAM Template for bot-dollar-currency

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  ExchangeRateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ExchangeRate/
      Handler: app.lambdaHandler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        ExchangeRate:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exchange
            Method: get
  NotificationServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: NotificationService/
      Handler: app.lambdaHandler
      Runtime: python3.9
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
      Architectures:
      - x86_64
      Events:
        ExchangeRate:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /notification
            Method: get
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "tauroluiseduardo@gmail.com"
          Protocol: "email"
      TopicName: "exchange-topic"
  FlowChart:
    Type: AWS::Serverless::StateMachine
      Properties:
        DefinitionUri: src/statemachine/process-order.asl.json
        DefinitionSubstitutions:
          ExchangeRateArn: !GetAtt ExchangeRateFunction.Arn
          NotificationServiceArn: !GetAtt NotificationServiceFunction.Arn

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExchangeRateApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ExchangeRateFunction:
    Description: "ExchangeRateLambda Function ARN"
    Value: !GetAtt ExchangeRateFunction.Arn
  ExchangeRateFunctionIamRole:
    Description: "Implicit IAM Role created for HelloExchangeRateFunction"
    Value: !GetAtt ExchangeRateFunction.Arn

